apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      name: http
  selector:
    app: backend
