apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: three-tier-app
  labels:
    app: backend
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "Aniket.Mori@1626" # Replace with your AWS RDS Password
